
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA DATE EXERCISE NUMBERlog : entriesentries : entry\n| entry entriesentry : DATE exercisesexercises : exercise\n| exercise exercisesexercise : EXERCISE NUMBER setssets : NUMBER\n| NUMBER COMMA sets'
    
_lr_action_items = {'DATE':([0,3,6,7,9,11,12,14,],[4,4,-4,-5,-6,-8,-7,-9,]),'$end':([1,2,3,5,6,7,9,11,12,14,],[0,-1,-2,-3,-4,-5,-6,-8,-7,-9,]),'EXERCISE':([4,7,11,12,14,],[8,8,-8,-7,-9,]),'NUMBER':([8,10,13,],[10,11,11,]),'COMMA':([11,],[13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'log':([0,],[1,]),'entries':([0,3,],[2,5,]),'entry':([0,3,],[3,3,]),'exercises':([4,7,],[6,9,]),'exercise':([4,7,],[7,7,]),'sets':([10,13,],[12,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> log","S'",1,None,None,None),
  ('log -> entries','log',1,'p_log','<stdin>',82),
  ('entries -> entry','entries',1,'p_entries','<stdin>',86),
  ('entries -> entry entries','entries',2,'p_entries','<stdin>',87),
  ('entry -> DATE exercises','entry',2,'p_entry','<stdin>',94),
  ('exercises -> exercise','exercises',1,'p_exercises','<stdin>',98),
  ('exercises -> exercise exercises','exercises',2,'p_exercises','<stdin>',99),
  ('exercise -> EXERCISE NUMBER sets','exercise',3,'p_exercise','<stdin>',106),
  ('sets -> NUMBER','sets',1,'p_sets','<stdin>',110),
  ('sets -> NUMBER COMMA sets','sets',3,'p_sets','<stdin>',111),
]
