
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA DATE EXERCISE NUMBERworkout : DATE exercisesexercises : exercise exercisesexercises : exerciseexercise : EXERCISE setssets : set COMMA setssets : setset : NUMBER NUMBERset : NUMBER'
    
_lr_action_items = {'DATE':([0,],[2,]),'$end':([1,3,4,6,7,8,9,11,12,],[0,-1,-3,-2,-4,-6,-8,-7,-5,]),'EXERCISE':([2,4,7,8,9,11,12,],[5,5,-4,-6,-8,-7,-5,]),'NUMBER':([5,9,10,],[9,11,9,]),'COMMA':([8,9,11,],[10,-8,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'workout':([0,],[1,]),'exercises':([2,4,],[3,6,]),'exercise':([2,4,],[4,4,]),'sets':([5,10,],[7,12,]),'set':([5,10,],[8,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> workout","S'",1,None,None,None),
  ('workout -> DATE exercises','workout',2,'p_workout','parser.py',40),
  ('exercises -> exercise exercises','exercises',2,'p_exercises_multiple','parser.py',45),
  ('exercises -> exercise','exercises',1,'p_exercises_single','parser.py',50),
  ('exercise -> EXERCISE sets','exercise',2,'p_exercise','parser.py',55),
  ('sets -> set COMMA sets','sets',3,'p_sets_multiple','parser.py',60),
  ('sets -> set','sets',1,'p_sets_single','parser.py',65),
  ('set -> NUMBER NUMBER','set',2,'p_set_weight_reps','parser.py',70),
  ('set -> NUMBER','set',1,'p_set_reps','parser.py',75),
]
